# Handlers for PXE provisioning

- name: restart dhcpd
  service:
    name: dhcpd
    state: restarted
  delegate_to: tftp-server-01

- name: restart dhcpd
  service:
    name: dhcpd
    state: restarted
  delegate_to: tftp-server-01
